field_mapping = {
    'business': 'business_&_finance',
    'international affairs': 'business_&_finance',
    'finance': 'business_&_finance',
    'economics': 'business_&_finance',
    'marketing': 'business_&_finance',
    'operations research': 'business_&_finance',
    'MBA': 'business_&_finance',
    'business administration': 'business_&_finance',
    'management': 'business_&_finance',
    
    'engineering': 'engineering_&_technology',
    'computer science': 'engineering_&_technology',
    'electrical engineering': 'engineering_&_technology',
    'mechanical engineering': 'engineering_&_technology',
    'civil engineering': 'engineering_&_technology',
    'industrial engineering': 'engineering_&_technology',
    'biomedical engineering': 'engineering_&_technology',
    'environmental engineering': 'engineering_&_technology',
    
    'natural science': 'natural_&_physical_sciences',
    'biology': 'natural_&_physical_sciences',
    'chemistry': 'natural_&_physical_sciences',
    'physics': 'natural_&_physical_sciences',
    'earth science': 'natural_&_physical_sciences',
    'ecology': 'natural_&_physical_sciences',
    'marine geophysics': 'natural_&_physical_sciences',
    'genetics': 'natural_&_physical_sciences',
    
    'social science': 'social_sciences',
    'anthropology': 'social_sciences',
    'sociology': 'social_sciences',
    'psychology': 'social_sciences',
    'political science': 'social_sciences',
    
    'law': 'law_&_public policy',
    'public policy': 'law_&_public policy',
    'international relations': 'law_&_public policy',
    'human rights': 'law_&_public policy',
    
    'healthcare': 'healthcare',
    'medicine': 'healthcare',
    'nursing': 'healthcare',
    'epidemiology': 'healthcare',
    'biomedicine': 'healthcare',
    'biotechnology': 'healthcare',
    'clinical psychology': 'healthcare',
    'speech pathology': 'healthcare',
    'nutrition': 'healthcare',
    
    'education': 'education',
    'teaching': 'education',
    'elementary education': 'education',
    'higher education': 'education',
    'educational psychology': 'education',
    'curriculum and teaching': 'education',
    'education administration': 'education',
    
    'creative arts': 'creative_arts',
    'arts administration': 'creative_arts',
    'theater': 'creative_arts',
    'film': 'creative_arts',
    'music': 'creative_arts',
    'art history': 'creative_arts',
    'creative writing': 'creative_arts',
    
    'humanities': 'humanities',
    'philosophy': 'humanities',
    'literature': 'humanities',
    'history': 'humanities',
    'religion': 'humanities',
    
    'mathematics': 'mathematics_&_statistics',
    'statistics': 'mathematics_&_statistics',
    'mathematical finance': 'mathematics_&_statistics',
    'quantitative methods': 'mathematics_&_statistics',
    
    'other': 'other'
}
